name: PlayerLogger
main: tech.ice.plugins.PlayerLogger.PlayerLogger
version: 1.0-SNAPSHOT
description: 記錄及查詢玩家資訊
author: ice
commands:
  lookup:
    description: 查詢玩家資訊
    aliases: [whois]
    usage: /lookup <玩家ID>